import { expect, test } from '@playwright/test';
import { openApp } from './helpers';

test('narrow task scope preserves workspace height and returns focus', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await openApp(page);
  const toggle = page.getByTestId('task-scope-toggle');
  await expect(page.locator('.ht-sidebar')).toBeHidden();
  const main = await page.locator('.ht-main').boundingBox();
  expect(main!.height).toBeGreaterThan(700);
  await toggle.click();
  const drawer = page.getByRole('dialog', { name: '当前视图的范围' });
  await expect(drawer).toBeVisible();
  await expect(drawer.getByText('标签', { exact: true })).toBeVisible();
  await drawer.getByRole('button', { name: '新建清单', exact: true }).click();
  const create = page.getByTestId('category-create-dialog');
  await expect(create).toBeVisible();
  await create.getByRole('textbox').fill('本周计划');
  await create.getByRole('button', { name: '创建清单', exact: true }).click();
  await expect(create).toBeHidden();
  await expect(drawer).toBeHidden();
  await expect(page.locator('.ht-header__title')).toHaveText('本周计划');
  await toggle.click();
  await drawer.getByRole('button', { name: '今天', exact: true }).click();
  await expect(drawer).toBeHidden();
  await expect(page.locator('.ht-header__title')).toHaveText('今天');
  await expect(toggle).toBeFocused();
  await toggle.click();
  await drawer.press('Escape');
  await expect(drawer).toBeHidden();
  await expect(toggle).toBeFocused();
  await toggle.click();
  await page.setViewportSize({ width: 1440, height: 900 });
  await expect(page.locator('.ht-scope-drawer')).toHaveCount(0);
  await expect(page.locator('.ht-sidebar')).toBeVisible();
  await expect(toggle).toBeHidden();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('dialog', { name: '当前视图的范围' })).toBeHidden();
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
});
