#!/bin/bash
#
# 鸿蒙 · JS 侧验收：**codegen / autolinking / JS bundle 全链路**（零桩）
# ==================================================================
#
# 🔴 它补的是上一轮**明确留下的那个缺口**
#
# `scripts/verify-harmony-rnoh.sh` 只验到"原生侧能编译"，它用**桩**顶替了：
#   · `autolink_libraries`  → no-op
#   · `PackageProvider.cpp` → 空实现
# 并诚实地写着：「不验 JS 侧 codegen/autolinking」。本脚本就是把那一环补上：
#
#   真实的 RN 工程（node_modules 里真有 react-native）
#     → RNOH 官方的 `@rnoh/hvigor-plugin` 跑真 codegen
#     → 真 autolinking 生成 `RNOHPackagesFactory.{h,ets}` + `autolinking.cmake`
#     → 真的 `pages/Index.ets`（RNOH 的 `RNApp` 根视图，从官方模板渲染）
#     → Metro 打出真 Hermes 字节码
#     → release HAP 把 bundle + 原生库都装进去
#
# ── 为什么这条判据值得单独存在
#
# "原生能编译" 与 "codegen 对不对" 是**两个独立的风险**。上一轮把前者验了、
# 后者留了桩；如果就此宣称"鸿蒙这条路通了"，那个桩就是一颗定时炸弹 ——
# 真 codegen 一跑才知道 `PackageProvider.cpp` 缺头文件、`autolinking.cmake`
# 缺函数、`pages/Index.ets` 根本不在模板里（真由 CLI 生成）。
# 本轮这些**全部真实发生过**（见 §3.25）。
#
# ── 它验什么（每一条都能失败）
#
#   1. Node **版本**：RN 0.84 的 CLI 要 `util.styleText`（Node ≥ 20.12），
#      而 DevEco 自带的是 **Node 18** —— 版本不够就**红**，并说清楚要怎么办。
#   2. codegen 真的产出了文件，且内容是 `generated by RNOH autolinking`（不是桩）。
#   3. Hermes bundle 的**魔数**真的是 `0x1F1903C103BC1FC6`（不是改了扩展名的 JS）。
#   4. release HAP 里真的有 `hermes_bundle.hbc` + 三个关键 `.so`。
#
# ── 它**不**验什么（诚实边界）
#
#   不验运行。缺模拟器系统镜像 + 签名（产物 unsigned）。**本脚本不对
#   "RN 应用在鸿蒙上跑得起来"下任何结论。**
#
# 用法：
#   pnpm verify:harmony-rnoh-js
#   可用 HEYTA_NODE_BIN 指定 Node ≥ 20.12（默认自动查找 nvm 的 v22/v20）。
#
# 依赖：DevEco Studio（SDK/NDK）、npm、一个 Node ≥ 20.12。

set -u
cd "$(dirname "$0")/.." || exit 1

DEVECO_HOME="${DEVECO_HOME:-/Applications/DevEco-Studio.app/Contents}"
# 🔴 必须用**短路径**：hvigor 内部 pnpm 会拿插件 tarball 的**绝对路径**当 store 索引文件名，
#    macOS 的 ${TMPDIR}（/var/folders/5n/...）会把它顶过 255 字节上限，报
#    `ERR_PNPM_ENAMETOOLONG`，而 hvigor 只往外抛一个笼统的 `00308002 Operation Error`（§7 第 62 条）。
WORK="${HEYTA_HARMONY_JS_WORK:-/tmp/heyta-harmony-rnjs}"
RNOH_VERSION="${RNOH_VERSION:-0.84.4}"
RN="${RN:-0.84.1}"
RNOH_HAR="${RNOH_HAR:-0.84.3}"

PASS=0; FAIL=0
step() { echo ""; echo "════ $1 ════"; }
ok()   { echo "   ✅ $1"; PASS=$((PASS+1)); }
bad()  { echo "   ❌ $1"; FAIL=$((FAIL+1)); }

echo ""
echo "=== 鸿蒙 JS 侧验收（codegen / autolinking / bundle，零桩）==="
echo "  DevEco: $DEVECO_HOME"
echo "  工作目录: $WORK"
echo "  RN $RN / RNOH CLI $RNOH_VERSION / HAR $RNOH_HAR"

# ── 第 0 步：前置（含 Node 版本这条硬判据）────────────────────

step "0. 前置：工具链 + 🔴 Node 版本"
[ -d "$DEVECO_HOME" ] || { echo "   ❌ 找不到 DevEco：$DEVECO_HOME"; exit 3; }
export DEVECO_SDK_HOME="$DEVECO_HOME/sdk"

for t in "$DEVECO_HOME/tools/ohpm/bin/ohpm" "$DEVECO_HOME/tools/hvigor/bin/hvigorw"; do
  [ -x "$t" ] && ok "$(basename "$t") 在位" || { bad "$t 缺失"; exit 3; }
done
NDK="$DEVECO_HOME/sdk/default/openharmony/native"
for t in "$NDK/build-tools/cmake/bin/cmake" "$NDK/build-tools/cmake/bin/ninja" "$NDK/llvm"; do
  [ -e "$t" ] && ok "NDK: $(basename "$t")" || { bad "NDK 缺 $t"; exit 3; }
done

# 🔴 这条不是形式主义：DevEco 自带的 node 就是 18.20.1，用它一定失败，
#    而且失败信息（`styleText is not a function`）完全看不出跟 Node 有关。
NODE_BIN="${HEYTA_NODE_BIN:-}"
if [ -z "$NODE_BIN" ]; then
  for cand in "$HOME"/.nvm/versions/node/v2[0-9].*/bin/node \
              /opt/homebrew/bin/node /usr/local/bin/node "$(command -v node 2>/dev/null)"; do
    [ -x "$cand" ] && { NODE_BIN="$cand"; break; }
  done
fi
if [ -x "${NODE_BIN:-}" ]; then
  NODE_VER=$("$NODE_BIN" -v | sed 's/^v//')
  MAJ=${NODE_VER%%.*}; REST=${NODE_VER#*.}; MIN=${REST%%.*}
  if [ "$MAJ" -gt 20 ] || { [ "$MAJ" -eq 20 ] && [ "$MIN" -ge 12 ]; }; then
    ok "Node ${NODE_VER}（≥ 20.12，满足 RN 0.84 CLI 的 util.styleText）"
  else
    bad "Node $NODE_VER 太旧：RN 0.84 的 CLI 需要 ≥ 20.12（DevEco 自带的 18.20.1 会报 styleText）"
    echo "      解决：装 Node 20+ 后 HEYTA_NODE_BIN=/path/to/node pnpm verify:harmony-rnoh-js"
    echo ""; echo "  通过 ${PASS}，失败 $FAIL"; exit 3
  fi
else
  bad "找不到 Node 可执行文件"; exit 3
fi
command -v npm >/dev/null 2>&1 && ok "npm 在位" || { bad "缺 npm"; exit 3; }

SDK_PKG="$DEVECO_HOME/sdk/default/sdk-pkg.json"
API=$(python3 -c "import json;print(json.load(open('$SDK_PKG'))['data']['apiVersion'])" 2>/dev/null)
SDK_NAME=$(python3 -c "import json;print(json.load(open('$SDK_PKG'))['data']['displayName'])" 2>/dev/null)
SDK_FULL="$(printf '%s' "${SDK_NAME:-}" | sed 's/HarmonyOS //')(${API})"
ok "SDK: ${SDK_NAME}（API ${API}）"

# ── 第 1 步：JS 侧工程 + 依赖 ───────────────────────────────

step "1. JS 侧（真 react-native，不是壳）"
mkdir -p "$WORK"
PROJ="$WORK/proj"
if [ ! -d "$PROJ/node_modules/react-native" ]; then
  rm -rf "$PROJ"; mkdir -p "$PROJ"
  cat > "$PROJ/package.json" <<EOF
{
  "name": "heyta",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@react-native-oh/react-native-harmony": "$RNOH_HAR",
    "react": "19.3.0",
    "react-native": "$RN"
  },
  "devDependencies": {
    "@react-native-community/cli": "latest",
    "@react-native-oh/react-native-harmony-cli": "$RNOH_VERSION",
    "@react-native/metro-config": "$RN",
    "metro": "^0.83.1"
  }
}
EOF
  cat > "$PROJ/index.js" <<'EOF'
// 最小 RN 根组件（用 createElement，探针不引入 babel 配置）
const React = require('react');
const { AppRegistry, View, Text } = require('react-native');
function App() {
  return React.createElement(
    View,
    { style: { flex: 1, alignItems: 'center', justifyContent: 'center' } },
    React.createElement(Text, null, 'heyta RNOH'),
  );
}
AppRegistry.registerComponent('heyta', () => App);
EOF
  cat > "$PROJ/metro.config.js" <<'EOF'
const { mergeConfig, getDefaultConfig } = require('@react-native/metro-config');
const { createHarmonyMetroConfig } = require('@react-native-oh/react-native-harmony/metro.config');
module.exports = mergeConfig(
  getDefaultConfig(__dirname),
  createHarmonyMetroConfig({ reactNativeHarmonyPackageName: '@react-native-oh/react-native-harmony' }),
);
EOF
  echo "   首次运行，装依赖（几分钟）……"
  ( cd "$PROJ" && PATH="$(dirname "$NODE_BIN"):$PATH" npm install --no-audit --no-fund \
      > /tmp/heyta-rnjs-npm.log 2>&1 ) && ok "npm install 成功" || { bad "npm install 失败"; exit 3; }
else
  ok "复用已有 node_modules"
fi
for d in react-native @react-native-oh/react-native-harmony @react-native-oh/react-native-harmony-cli hermes-compiler; do
  [ -d "$PROJ/node_modules/$d" ] && ok "node_modules/$d" || bad "缺 node_modules/$d"
done

# ── 第 2 步：鸿蒙脚手架（官方模板 + 真插件）─────────────────

step "2. 鸿蒙脚手架（官方 CLI 模板，接真插件）"
CLI_DIR="$WORK/_cli"
if [ ! -d "$CLI_DIR/package" ]; then
  rm -rf "$CLI_DIR"; mkdir -p "$CLI_DIR"
  ( cd "$CLI_DIR" && PATH="$(dirname "$NODE_BIN"):$PATH" npm pack \
      "@react-native-oh/react-native-harmony-cli@$RNOH_VERSION" >/dev/null 2>&1 && tar xzf ./*.tgz )
fi
CLI_PKG="$CLI_DIR/package"
TEMPLATE="$CLI_PKG/src/init/templates/harmony"
if [ -d "$TEMPLATE" ]; then ok "官方模板就位"; else bad "取不到官方模板"; exit 3; fi

HARMONY="$PROJ/harmony"
rm -rf "$HARMONY"; mkdir -p "$HARMONY"
cp -R "$TEMPLATE"/. "$HARMONY"/
find "$HARMONY" -name "gitignore" -delete

python3 - "$PROJ" "$HARMONY" "$SDK_FULL" "$RNOH_VERSION" "$CLI_PKG" <<'PY'
import io, json, os, re, sys
proj, harmony, sdk_full, cli_ver, cli_pkg = sys.argv[1:6]

# SDK 版本：读实际值，不写死（模板里是旧的 5.0.0(12)）
bp = os.path.join(harmony, 'build-profile.json5')
s = io.open(bp, encoding='utf-8').read()
s = re.sub(r"compatibleSdkVersion:\s*'[^']*'", f"compatibleSdkVersion: '{sdk_full}'", s)
s = re.sub(r"targetSdkVersion:\s*'[^']*'", f"targetSdkVersion: '{sdk_full}'", s)
io.open(bp, 'w', encoding='utf-8').write(s)

# bundleName：模板是 `com.example`（两段），过不了 hvigor 的 schema（要三段）
aj = os.path.join(harmony, 'AppScope/app.json5')
s = io.open(aj, encoding='utf-8').read()
s = s.replace('"bundleName": "com.example"', '"bundleName": "com.heyta.harmony"')
s = s.replace('"vendor": "example"', '"vendor": "heyta"')
io.open(aj, 'w', encoding='utf-8').write(s)

# 根 oh-package.json5（模板没有；由 CLI 的 OhPackageJson5Template 生成）
io.open(os.path.join(harmony, 'oh-package.json5'), 'w', encoding='utf-8').write('''{
  "modelVersion": "5.0.0",
  "description": "heyta HarmonyOS shell",
  "dependencies": { "@rnoh/react-native-openharmony": "0.84.3" },
  "devDependencies": {}
}
''')

# 真插件：hvigor-config 里按 CLI 自带 tgz 接进去（**不用桩**）
io.open(os.path.join(harmony, 'hvigor/hvigor-config.json5'), 'w', encoding='utf-8').write(
    "{\n  modelVersion: '5.0.0',\n  dependencies: {\n"
    f'    "@rnoh/hvigor-plugin": "../../node_modules/@react-native-oh/react-native-harmony-cli/harmony/rnoh-hvigor-plugin-{cli_ver}.tgz",\n'
    "  },\n}\n")

# 🔴 `pages/Index.ets` **不在模板里** —— 真货由 CLI 的 EntryIndexTemplate 生成。
#    这里从官方模板**渲染**它，而不是手抄一份（手抄会漂移）。
src = io.open(os.path.join(cli_pkg, 'src/init/templates/EntryIndexTemplate.ts'),
              encoding='utf-8').read()
m = re.search(r'const TEMPLATE = `\n(.*?)`;', src, re.S)
assert m, "EntryIndexTemplate 的模板格式变了"
index_ets = m.group(1).replace('{{name}}', 'heyta')
os.makedirs(os.path.join(harmony, 'entry/src/main/ets/pages'), exist_ok=True)
io.open(os.path.join(harmony, 'entry/src/main/ets/pages/Index.ets'), 'w', encoding='utf-8').write(index_ets)
print("   脚手架已按实际环境改写；Index.ets 由官方 EntryIndexTemplate 渲染")
PY
[ -f "$HARMONY/entry/src/main/ets/pages/Index.ets" ] && ok "Index.ets 就位（RNApp 根视图）" || bad "Index.ets 生成失败"

# ── 第 3 步：真 codegen + 真 autolinking ────────────────────

step "3. ohpm install → hvigorw（真 codegen + 真 autolinking）"
export NODE_HOME="$(dirname "$(dirname "$NODE_BIN")")"
export PATH="$(dirname "$NODE_BIN"):$DEVECO_HOME/tools/ohpm/bin:$DEVECO_HOME/tools/hvigor/bin:$PATH"
cd "$HARMONY" || exit 1
ohpm install > /tmp/heyta-rnjs-ohpm.log 2>&1 && ok "ohpm install" || bad "ohpm install 失败"

LOG=/tmp/heyta-rnjs-hvigor.log
hvigorw assembleHap --mode module -p product=default -p buildMode=debug --no-daemon > "$LOG" 2>&1 \
  && ok "hvigorw assembleHap 退出码 0" \
  || { bad "hvigorw assembleHap 失败"
       # hvigor 只抛笼统的 00308002，真因在它启动的 pnpm 里 —— 把它捞出来说清楚。
       if grep -q "ENAMETOOLONG" "$LOG"; then
         echo "      🔴 真因是 ERR_PNPM_ENAMETOOLONG：工程路径太长（hvigor 用插件 tarball 的"
         echo "         绝对路径当 pnpm store 文件名，255 字节上限）。把工作目录换成短路径，"
         echo "         例如 /tmp/... —— 别用 macOS 的 \$TMPDIR（/var/folders/...，见 §7 第 62 条）。"
       fi
       grep -E "ERROR|error:|ENAMETOOLONG" "$LOG" | head -6 | sed 's/^/      /'; }

# 🔴 codegen/autolinking 的产物必须是**真货**，不是桩。
#    判据：文件头写着 "generated by RNOH autolinking"（桩不可能有这句）。
GEN_CPP="$HARMONY/entry/src/main/cpp/RNOHPackagesFactory.h"
GEN_ETS="$HARMONY/entry/src/main/ets/RNOHPackagesFactory.ets"
GEN_CMAKE="$HARMONY/entry/src/main/cpp/autolinking.cmake"
for f in "$GEN_CPP" "$GEN_ETS" "$GEN_CMAKE"; do
  if [ -f "$f" ] && grep -q "generated by RNOH autolinking" "$f"; then
    ok "autolinking 真产物：$(basename "$f")"
  else
    bad "缺真 autolinking 产物或被桩顶替：$(basename "$f")"
  fi
done
[ -f "$HARMONY/entry/src/main/cpp/generated/RNOHGeneratedPackage.h" ] \
  && ok "codegen 产物：RNOHGeneratedPackage.h" || bad "缺 codegen 产物 RNOHGeneratedPackage.h"

# ── 第 4 步：真 bundle（Metro → Hermes 字节码）──────────────

step "4. bundle-harmony（真 Hermes 字节码）"
# 🔴 hermesc 不在 `react-native/sdks/hermesc/`（bundle-harmony 默认去那找，会报
#    "Couldn't find hermesc"），它由 `hermes-compiler` 包提供 → 必须 --hermesc-dir。
HBC="$HARMONY/entry/src/main/resources/rawfile/hermes_bundle.hbc"
mkdir -p "$(dirname "$HBC")"
cd "$PROJ" || exit 1
node_modules/.bin/react-native bundle-harmony \
  --entry-file index.js --bundle-output "$HBC" \
  --assets-dest "$HARMONY/entry/src/main/resources/rawfile/assets" \
  --js-engine hermes --dev false \
  --hermesc-dir node_modules/hermes-compiler/hermesc > /tmp/heyta-rnjs-bundle.log 2>&1 \
  && ok "bundle-harmony 退出码 0" \
  || { bad "bundle-harmony 失败"; grep -iE "error|Couldn't" /tmp/heyta-rnjs-bundle.log | head -4 | sed 's/^/      /'; }

if [ -f "$HBC" ]; then
  # 扩展名可以随便起，**魔数**不行 —— 验它，别验文件名。
  MAGIC=$(python3 -c "
import io,struct
b=io.open('$HBC','rb').read(8)
print('0x%X' % struct.unpack('<Q',b)[0] if len(b)==8 else 'short')
" 2>/dev/null)
  if [ "$MAGIC" = "0x1F1903C103BC1FC6" ]; then
    ok "Hermes 魔数正确（$(ls -lh "$HBC" | awk '{print $5}')）"
  else
    bad "不是 Hermes 字节码（魔数 ${MAGIC}）—— 可能是改了扩展名的 JS"
  fi
else
  bad "没有产出 hermes_bundle.hbc"
fi

# ── 第 5 步：release HAP（bundle 要进包）────────────────────

step "5. release HAP：验证 bundle 与原生库真的进包"
cd "$HARMONY" || exit 1
LOG=/tmp/heyta-rnjs-release.log
hvigorw assembleHap --mode module -p product=default -p buildMode=release --no-daemon > "$LOG" 2>&1 \
  && ok "release 构建退出码 0" \
  || { bad "release 构建失败"; grep -E "ERROR|error:" "$LOG" | head -6 | sed 's/^/      /'; }

HAP=$(find "$HARMONY" -name "*.hap" -not -path "*/oh_modules/*" 2>/dev/null | head -1)
if [ -n "$HAP" ]; then
  ok "产出 $(basename "$HAP")（$(ls -lh "$HAP" | awk '{print $5}')）"
  unzip -l "$HAP" > /tmp/heyta-rnjs-haplist.txt 2>/dev/null
  grep -q "rawfile/hermes_bundle.hbc" /tmp/heyta-rnjs-haplist.txt \
    && ok "HAP 内含 hermes_bundle.hbc（自包含，不依赖 Metro）" \
    || bad "HAP 内没有 hermes_bundle.hbc —— 装到设备上会连不上 Metro 白屏"
  for lib in librnoh_core.so librnoh_app.so libreactnative.so; do
    grep -q "$lib" /tmp/heyta-rnjs-haplist.txt && ok "HAP 内含 $lib" || bad "HAP 缺 $lib"
  done
else
  bad "没有产出 .hap"
fi

# ── 汇总 ───────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════"
echo "  通过 $PASS 项，失败 $FAIL 项"
if [ "$FAIL" -eq 0 ]; then
  echo "  ✅ 鸿蒙 JS 侧全链路：codegen + autolinking + Metro/Hermes bundle + release HAP"
  echo ""
  echo "  ⚠️ 边界：**不验运行** —— 缺模拟器系统镜像 + 签名（产物 unsigned）。"
  echo "     这不等同于「RN 应用在鸿蒙上跑得起来」。"
  exit 0
fi
echo "  ❌ 有失败项"
exit 1